
# SEO settings
title: "Nan Jiang"
title2: "Blog site" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://jiangnanhugo.github.io/blog # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-91769229-1
repo: http://github.com/jiangnanhugo/blog
disqus_shortname: "nanjiang"
twitter_username: "nanjiang"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nan Jiang"
  job      : "Undergraduate Student"
  bio      : "Coding Myself."
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : http://jiangnanhugo.github.io
  github   : http://github.com/jiangnanhugo
  twitter  : http://twitter.com/HeiswayiNrird
  facebook : https://www.facebook.com/profile.php?id=1257583160
  linkedin : https://www.linkedin.com/in/%E6%A5%A0-%E5%A7%9C-097922aa/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
